<?php

declare(strict_types=1);

/**
 * Reference configuration.
 *
 * The installer writes config/config.php from this shape with real values.
 * That file is in .gitignore and is listed as a protected path, so the updater
 * will never overwrite it — this sample is what ships in the repository.
 *
 * Every brand string lives here. Nothing in app/ or the views hardcodes a
 * product name, domain or colour; that is what makes white-labelling possible.
 */

return [
    'app' => [
        'name'            => 'AK Connect',
        'version'         => '1.0.0',
        'env'             => 'production',   // production | staging | local
        'debug'           => false,          // NEVER true in production
        'url'             => 'https://net.akdwk.in',
        'domain'          => 'net.akdwk.in',
        'base_path'       => '',             // '' at the domain root, '/panel' in a subfolder
        'timezone'        => 'Asia/Kolkata',
        'locale'          => 'en',
        'key'             => '',             // base64:... generated by the installer
        'trusted_proxies' => [],             // e.g. ['127.0.0.1'] behind nginx/Cloudflare
        'installed_at'    => null,
    ],

    'brand' => [
        'name'          => 'AK Connect',
        'org'           => 'AK Computer',
        'support_email' => 'support@net.akdwk.in',
        'logo'          => '',               // path under uploads/, empty = wordmark
        'primary_color' => '#2563eb',
        'accent_color'  => '#0ea5e9',
        'powered_by'    => true,             // Enterprise tenants may switch this off
    ],

    'db' => [
        'host'           => '127.0.0.1',
        'port'           => 3306,
        'name'           => 'akconnect',
        'user'           => 'akconnect',
        'pass'           => '',
        'prefix'         => '',
        'read_host'      => null,            // set to a replica hostname to split reads
        'slow_query_ms'  => 500,
    ],

    'redis' => [
        'enabled' => false,
        'host'    => '127.0.0.1',
        'port'    => 6379,
        'pass'    => '',
        'db'      => 0,
    ],

    'session' => [
        'name'             => 'ak_session',
        'lifetime_minutes' => 720,
        'idle_minutes'     => 240,
    ],

    'security' => [
        'password_min_length'  => 10,
        'lockout_threshold'    => 5,
        'lockout_max_seconds'  => 3600,
        'require_2fa_super'    => true,
        'api_rate_per_minute'  => 120,
        'login_rate_per_15min' => 20,
        'enroll_rate_per_hour' => 60,
        'hsts_max_age'         => 31536000,
        // Public half of the controller's ed25519 identity. Agents verify their
        // cached config against this, so a spoofed controller cannot inject peers.
        'controller_public_key' => '',
        // Public key that update.json manifests are signed with (§9.3).
        'update_public_key'     => '',
    ],

    'mail' => [
        'host'        => '',
        'port'        => 587,
        'user'        => '',
        'pass'        => '',
        'security'    => 'tls',              // tls | ssl | none
        'from'        => 'no-reply@net.akdwk.in',
        'from_name'   => 'AK Connect',
        'verify_peer' => true,
        'timeout'     => 15,
    ],

    'coordinator' => [
        'host'          => '127.0.0.1',
        'port'          => 8443,
        'internal_url'  => 'http://127.0.0.1:8080',
        'shared_secret' => '',               // HMAC secret for panel <-> coordinator
        'public_host'   => 'coord.net.akdwk.in',
    ],

    'relays' => [
        // Bootstrap list handed to agents before they learn the live set.
        // ['name' => 'in-bom-1', 'host' => 'relay1.net.akdwk.in', 'port' => 51820, 'public_key' => '...']
    ],

    'network' => [
        'default_cidr'      => '10.50.0.0/16',
        'default_mtu'       => 1280,
        'default_keepalive' => 25,
        'default_dns'       => ['1.1.1.1', '8.8.8.8'],
        'join_code_ttl_min' => 60,
        // R1: the tunnel never carries a default route. Kept here as an explicit,
        // auditable switch rather than an implicit property of the agent code.
        'allow_default_route' => false,
    ],

    'update' => [
        'github_api'       => 'https://api.github.com',
        'timeout_seconds'  => 120,
        'user_agent'       => 'AK-Connect-Updater',
        'cache_minutes'    => 15,
        'min_free_disk_multiplier' => 3,
    ],

    'backup' => [
        // Deliberately separate from app.key: a leaked application key must not
        // also decrypt the off-site backups.
        'encryption_key'     => '',
        'max_uploads_bytes'  => 2147483648,  // skip uploads/ in a backup above 2 GB
        'offsite_driver'     => 'none',      // none | s3 | ftp
        'offsite'            => [],
    ],

    'logging' => [
        'level'          => 'info',          // debug | info | notice | warning | error
        'retention_days' => 30,
    ],
];
