<?php

declare(strict_types=1);

namespace App\Models;

use App\Core\DB;
use App\Core\NotFoundException;
use App\Middleware\TenantScope;

/**
 * Base model.
 *
 * Two properties carry the weight here:
 *   $tenantScoped — when true, *every* read and write generated by this class
 *                   passes through TenantScope::constrain(). There is no code
 *                   path that skips it.
 *   $fillable     — an allow-list. Anything not named is dropped before the
 *                   INSERT/UPDATE is built, so a crafted form field cannot set
 *                   tenant_id, status or role.
 *
 * Column names are never taken from user input: they are validated against
 * $fillable / $sortable before being placed in SQL, and values are always bound.
 */
abstract class Model
{
    protected static string $table = '';
    protected static bool $tenantScoped = true;
    protected static bool $softDeletes = true;
    /** @var list<string> */
    protected static array $fillable = [];
    /** @var list<string> columns a client may sort by */
    protected static array $sortable = ['id', 'created_at', 'updated_at'];
    /** @var list<string> columns stored as JSON, decoded on read */
    protected static array $jsonColumns = [];

    public static function tableName(): string
    {
        return DB::table(static::$table);
    }

    public static function isTenantScoped(): bool
    {
        return static::$tenantScoped;
    }

    // -------------------------------------------------------------- reading

    /** @return array<string,mixed>|null */
    public static function find(int $id): ?array
    {
        $bindings = ['id' => $id];
        $where = 'id = :id';
        if (static::$softDeletes) {
            $where .= ' AND deleted_at IS NULL';
        }
        if (static::$tenantScoped) {
            $where = TenantScope::constrain($where, $bindings);
        }

        $row = DB::selectOne('SELECT * FROM ' . static::tableName() . ' WHERE ' . $where . ' LIMIT 1', $bindings);

        return $row === null ? null : static::hydrate($row);
    }

    /**
     * @return array<string,mixed>
     * @throws NotFoundException
     */
    public static function findOrFail(int $id): array
    {
        $row = static::find($id);
        if ($row === null) {
            // A row that exists but belongs to another tenant is reported as
            // missing, not forbidden — a 403 would confirm that the id exists.
            throw new NotFoundException(static::class . ' #' . $id . ' not found');
        }

        return $row;
    }

    /**
     * Fetch by an arbitrary equality filter.
     *
     * @param array<string,mixed> $conditions column => value; columns are
     *                                        checked against the table's
     *                                        allow-list before use.
     * @return array<string,mixed>|null
     */
    public static function findBy(array $conditions): ?array
    {
        [$where, $bindings] = static::buildWhere($conditions);
        $row = DB::selectOne('SELECT * FROM ' . static::tableName() . ' WHERE ' . $where . ' LIMIT 1', $bindings);

        return $row === null ? null : static::hydrate($row);
    }

    /**
     * @param array<string,mixed> $conditions
     * @return list<array<string,mixed>>
     */
    public static function where(array $conditions, string $orderBy = 'id', string $direction = 'ASC', int $limit = 0): array
    {
        [$where, $bindings] = static::buildWhere($conditions);
        $sql = 'SELECT * FROM ' . static::tableName() . ' WHERE ' . $where
            . ' ORDER BY ' . static::safeColumn($orderBy) . ' ' . static::safeDirection($direction);
        if ($limit > 0) {
            $sql .= ' LIMIT ' . max(1, min($limit, 1000));
        }

        return array_map(static::hydrate(...), DB::select($sql, $bindings));
    }

    /** @param array<string,mixed> $conditions */
    public static function count(array $conditions = []): int
    {
        [$where, $bindings] = static::buildWhere($conditions);

        return (int) DB::scalar('SELECT COUNT(*) FROM ' . static::tableName() . ' WHERE ' . $where, $bindings);
    }

    public static function exists(int $id): bool
    {
        return static::find($id) !== null;
    }

    /**
     * Paginated list with a total count.
     *
     * @param array<string,mixed> $conditions
     * @return array{rows:list<array<string,mixed>>,total:int,page:int,per_page:int,pages:int}
     */
    public static function paginate(
        array $conditions = [],
        int $page = 1,
        int $perPage = 25,
        string $orderBy = 'id',
        string $direction = 'DESC',
        string $searchTerm = '',
        array $searchColumns = []
    ): array {
        $page = max(1, $page);
        $perPage = max(1, min($perPage, 200));

        [$where, $bindings] = static::buildWhere($conditions);

        if ($searchTerm !== '' && $searchColumns !== []) {
            $clauses = [];
            foreach ($searchColumns as $i => $column) {
                $bind = 'search' . $i;
                $clauses[] = static::safeColumn($column) . ' LIKE :' . $bind;
                // Escape LIKE wildcards so a search for "%" is a literal search.
                $bindings[$bind] = '%' . addcslashes($searchTerm, '%_\\') . '%';
            }
            $where = '(' . $where . ') AND (' . implode(' OR ', $clauses) . ')';
        }

        $total = (int) DB::scalar('SELECT COUNT(*) FROM ' . static::tableName() . ' WHERE ' . $where, $bindings);

        $sql = 'SELECT * FROM ' . static::tableName() . ' WHERE ' . $where
            . ' ORDER BY ' . static::safeColumn($orderBy) . ' ' . static::safeDirection($direction)
            . ' LIMIT ' . $perPage . ' OFFSET ' . (($page - 1) * $perPage);

        $rows = array_map(static::hydrate(...), DB::select($sql, $bindings));

        return [
            'rows'     => $rows,
            'total'    => $total,
            'page'     => $page,
            'per_page' => $perPage,
            'pages'    => (int) ceil($total / $perPage),
        ];
    }

    // -------------------------------------------------------------- writing

    /** @param array<string,mixed> $attributes */
    public static function create(array $attributes): int
    {
        $data = static::filterFillable($attributes);

        if (static::$tenantScoped && !isset($data['tenant_id'])) {
            $tenantId = TenantScope::currentTenantId();
            if ($tenantId === null) {
                throw new \App\Core\AppException(
                    'Refusing to insert into tenant-scoped table ' . static::$table . ' without a tenant_id.'
                );
            }
            $data['tenant_id'] = $tenantId;
        }

        $data = static::encodeJsonColumns($data);

        $columns = array_keys($data);
        $placeholders = array_map(static fn (string $c): string => ':' . $c, $columns);

        $sql = 'INSERT INTO ' . static::tableName()
            . ' (' . implode(', ', array_map(static fn (string $c): string => '`' . $c . '`', $columns)) . ')'
            . ' VALUES (' . implode(', ', $placeholders) . ')';

        DB::execute($sql, $data);

        return DB::lastInsertId();
    }

    /** @param array<string,mixed> $attributes */
    public static function update(int $id, array $attributes): bool
    {
        $data = static::filterFillable($attributes);
        // tenant_id is never reassignable through a normal update.
        unset($data['tenant_id']);
        if ($data === []) {
            return false;
        }
        $data = static::encodeJsonColumns($data);

        $assignments = [];
        foreach (array_keys($data) as $column) {
            $assignments[] = '`' . $column . '` = :' . $column;
        }

        $bindings = $data;
        $bindings['__id'] = $id;
        $where = 'id = :__id';
        if (static::$softDeletes) {
            $where .= ' AND deleted_at IS NULL';
        }
        if (static::$tenantScoped) {
            $where = TenantScope::constrain($where, $bindings);
        }

        $sql = 'UPDATE ' . static::tableName() . ' SET ' . implode(', ', $assignments)
            . ', updated_at = UTC_TIMESTAMP() WHERE ' . $where;

        return DB::execute($sql, $bindings)->rowCount() > 0;
    }

    /** Soft delete where supported, hard delete otherwise. */
    public static function delete(int $id): bool
    {
        $bindings = ['__id' => $id];
        $where = 'id = :__id';
        if (static::$tenantScoped) {
            $where = TenantScope::constrain($where, $bindings);
        }

        $sql = static::$softDeletes
            ? 'UPDATE ' . static::tableName() . ' SET deleted_at = UTC_TIMESTAMP(), updated_at = UTC_TIMESTAMP() WHERE ' . $where . ' AND deleted_at IS NULL'
            : 'DELETE FROM ' . static::tableName() . ' WHERE ' . $where;

        return DB::execute($sql, $bindings)->rowCount() > 0;
    }

    public static function forceDelete(int $id): bool
    {
        $bindings = ['__id' => $id];
        $where = 'id = :__id';
        if (static::$tenantScoped) {
            $where = TenantScope::constrain($where, $bindings);
        }

        return DB::execute('DELETE FROM ' . static::tableName() . ' WHERE ' . $where, $bindings)->rowCount() > 0;
    }

    // ------------------------------------------------------------ internals

    /**
     * @param array<string,mixed> $conditions
     * @return array{0:string,1:array<string,mixed>}
     */
    protected static function buildWhere(array $conditions): array
    {
        $clauses = [];
        $bindings = [];

        foreach ($conditions as $column => $value) {
            $safe = static::safeColumn($column);
            $bind = 'w_' . preg_replace('/[^a-z0-9_]/i', '_', $column);

            if ($value === null) {
                $clauses[] = $safe . ' IS NULL';
                continue;
            }
            if (is_array($value)) {
                if ($value === []) {
                    $clauses[] = '1 = 0'; // IN () is a syntax error; match nothing
                    continue;
                }
                $in = [];
                foreach (array_values($value) as $i => $item) {
                    $in[] = ':' . $bind . '_' . $i;
                    $bindings[$bind . '_' . $i] = $item;
                }
                $clauses[] = $safe . ' IN (' . implode(', ', $in) . ')';
                continue;
            }

            $clauses[] = $safe . ' = :' . $bind;
            $bindings[$bind] = $value;
        }

        if (static::$softDeletes && !array_key_exists('deleted_at', $conditions)) {
            $clauses[] = 'deleted_at IS NULL';
        }

        $where = $clauses === [] ? '1 = 1' : implode(' AND ', $clauses);

        if (static::$tenantScoped) {
            $where = TenantScope::constrain($where, $bindings);
        }

        return [$where, $bindings];
    }

    /**
     * Column names reach SQL only through here. Anything that is not a plain
     * identifier is rejected outright rather than escaped, so there is no
     * quoting subtlety to get wrong.
     */
    protected static function safeColumn(string $column): string
    {
        if (preg_match('/^[a-z_][a-z0-9_]*$/i', $column) !== 1) {
            throw new \App\Core\AppException('Invalid column name: ' . $column);
        }

        return '`' . $column . '`';
    }

    protected static function safeDirection(string $direction): string
    {
        return strtoupper($direction) === 'ASC' ? 'ASC' : 'DESC';
    }

    /** @param array<string,mixed> $attributes @return array<string,mixed> */
    protected static function filterFillable(array $attributes): array
    {
        if (static::$fillable === []) {
            return $attributes;
        }

        return array_intersect_key($attributes, array_flip(static::$fillable));
    }

    /** @param array<string,mixed> $data @return array<string,mixed> */
    protected static function encodeJsonColumns(array $data): array
    {
        foreach (static::$jsonColumns as $column) {
            if (array_key_exists($column, $data) && (is_array($data[$column]) || is_object($data[$column]))) {
                $data[$column] = json_encode($data[$column], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
            }
        }

        return $data;
    }

    /** @param array<string,mixed> $row @return array<string,mixed> */
    protected static function hydrate(array $row): array
    {
        foreach (static::$jsonColumns as $column) {
            if (isset($row[$column]) && is_string($row[$column])) {
                $decoded = json_decode($row[$column], true);
                $row[$column] = is_array($decoded) ? $decoded : null;
            }
        }

        return $row;
    }
}
